services:
  app:
    build: ./restaurantes_app_front
    ports:
      - "5173:5173"
    volumes:
      - ./restaurantes_app_front/src:/app/src

  api:
    build: ./restaurantes_app_back
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"



volumes:
  postgres_data:
